const path = require('path');
require('dotenv').config({ path: path.resolve(__dirname, '../../../.env') });

if (process.env.CONFIRM_DEMO_SEED !== 'yes') {
  throw new Error('Refusing destructive seed without CONFIRM_DEMO_SEED=yes');
}

const db = require('../models');

const seed = async () => {
  try {
    await db.sequelize.authenticate();
    console.log('Database connected.');

    await db.sequelize.sync({ force: true });
    console.log('All models synced (tables reset).');

    // ===== USERS =====
    const admin = await db.User.create({
      email: 'admin@disaster-response.gov',
      password: 'Admin123!',
      name: 'Director Sarah Mitchell',
      role: 'admin',
      department: 'Emergency Management',
      phone: '202-555-0100',
      isActive: true,
    });

    const users = await db.User.bulkCreate([
      { email: 'jthompson@disaster-response.gov', password: 'Pass123!', name: 'James Thompson', role: 'coordinator', department: 'Field Operations', phone: '202-555-0101', isActive: true },
      { email: 'mchen@disaster-response.gov', password: 'Pass123!', name: 'Maria Chen', role: 'coordinator', department: 'Logistics', phone: '202-555-0102', isActive: true },
      { email: 'rwilson@disaster-response.gov', password: 'Pass123!', name: 'Robert Wilson', role: 'coordinator', department: 'Medical Response', phone: '202-555-0103', isActive: true },
      { email: 'kbrown@disaster-response.gov', password: 'Pass123!', name: 'Karen Brown', role: 'volunteer', department: 'Search & Rescue', phone: '202-555-0104', isActive: true },
      { email: 'djohnson@disaster-response.gov', password: 'Pass123!', name: 'David Johnson', role: 'volunteer', department: 'Communications', phone: '202-555-0105', isActive: true },
      { email: 'lgarcia@disaster-response.gov', password: 'Pass123!', name: 'Lisa Garcia', role: 'coordinator', department: 'Shelter Management', phone: '202-555-0106', isActive: true },
      { email: 'mlee@disaster-response.gov', password: 'Pass123!', name: 'Michael Lee', role: 'volunteer', department: 'Transportation', phone: '202-555-0107', isActive: true },
      { email: 'spatel@disaster-response.gov', password: 'Pass123!', name: 'Sunita Patel', role: 'coordinator', department: 'Public Health', phone: '202-555-0108', isActive: true },
      { email: 'tanderson@disaster-response.gov', password: 'Pass123!', name: 'Tom Anderson', role: 'volunteer', department: 'Infrastructure', phone: '202-555-0109', isActive: true },
      { email: 'jrivera@disaster-response.gov', password: 'Pass123!', name: 'Jennifer Rivera', role: 'volunteer', department: 'Donations', phone: '202-555-0110', isActive: true },
      { email: 'bsmith@disaster-response.gov', password: 'Pass123!', name: 'Brian Smith', role: 'coordinator', department: 'Hazmat', phone: '202-555-0111', isActive: true },
      { email: 'awright@disaster-response.gov', password: 'Pass123!', name: 'Angela Wright', role: 'volunteer', department: 'Mental Health', phone: '202-555-0112', isActive: true },
      { email: 'cmartin@disaster-response.gov', password: 'Pass123!', name: 'Carlos Martin', role: 'volunteer', department: 'Fire Services', phone: '202-555-0113', isActive: true },
      { email: 'nkim@disaster-response.gov', password: 'Pass123!', name: 'Nancy Kim', role: 'coordinator', department: 'Planning', phone: '202-555-0114', isActive: true },
    ], { individualHooks: true });
    console.log('Users seeded.');

    // ===== INCIDENTS =====
    const incidents = await db.Incident.bulkCreate([
      { title: 'Hurricane Elena - Gulf Coast', type: 'hurricane', severity: 5, status: 'active', location: 'Houston, TX', latitude: 29.7604, longitude: -95.3698, description: 'Category 4 hurricane making landfall along the Texas Gulf Coast with sustained winds of 145 mph and storm surge of 15-20 feet.', affectedPopulation: 2500000, startDate: new Date('2026-03-15'), commanderName: 'Director Sarah Mitchell', estimatedDamage: 45000000000 },
      { title: 'California Wildfire Complex - Sierra Nevada', type: 'wildfire', severity: 4, status: 'active', location: 'Paradise, CA', latitude: 39.7596, longitude: -121.6219, description: 'Multiple wildfire complexes burning across 150,000 acres in the Sierra Nevada foothills, threatening 12 communities.', affectedPopulation: 85000, startDate: new Date('2026-03-10'), commanderName: 'James Thompson', estimatedDamage: 3200000000 },
      { title: 'Midwest Tornado Outbreak', type: 'tornado', severity: 4, status: 'active', location: 'Joplin, MO', latitude: 37.0842, longitude: -94.5133, description: 'Outbreak of 23 tornadoes across Missouri, Kansas, and Oklahoma. Multiple EF4 and EF5 tornadoes confirmed.', affectedPopulation: 320000, startDate: new Date('2026-03-14'), commanderName: 'Robert Wilson', estimatedDamage: 8500000000 },
      { title: 'Mississippi River Flooding', type: 'flood', severity: 3, status: 'monitoring', location: 'Memphis, TN', latitude: 35.1495, longitude: -90.0490, description: 'Record flooding along the Mississippi River from Memphis to Baton Rouge. Levee breaches reported in 3 locations.', affectedPopulation: 450000, startDate: new Date('2026-03-08'), commanderName: 'Maria Chen', estimatedDamage: 12000000000 },
      { title: 'Pacific Northwest Earthquake', type: 'earthquake', severity: 5, status: 'active', location: 'Seattle, WA', latitude: 47.6062, longitude: -122.3321, description: 'Magnitude 7.1 earthquake along the Cascadia Subduction Zone. Widespread structural damage across Seattle and Tacoma.', affectedPopulation: 3800000, startDate: new Date('2026-03-16'), commanderName: 'Director Sarah Mitchell', estimatedDamage: 65000000000 },
      { title: 'Chemical Plant Explosion - Baton Rouge', type: 'chemical_spill', severity: 4, status: 'active', location: 'Baton Rouge, LA', latitude: 30.4515, longitude: -91.1871, description: 'Major chemical plant explosion releasing toxic chlorine gas. 5-mile evacuation zone established.', affectedPopulation: 125000, startDate: new Date('2026-03-17'), commanderName: 'Brian Smith', estimatedDamage: 890000000 },
      { title: 'Hawaii Tsunami Warning', type: 'tsunami', severity: 3, status: 'monitoring', location: 'Honolulu, HI', latitude: 21.3069, longitude: -157.8583, description: 'Tsunami warning issued following 8.2 earthquake in the Aleutian Islands. Wave arrival estimated in 4 hours.', affectedPopulation: 980000, startDate: new Date('2026-03-17'), commanderName: 'Karen Brown', estimatedDamage: 500000000 },
      { title: 'Avian Flu Outbreak - Midwest', type: 'pandemic', severity: 2, status: 'monitoring', location: 'Des Moines, IA', latitude: 41.5868, longitude: -93.6250, description: 'H5N1 avian influenza outbreak detected in poultry farms across Iowa and Nebraska. 15 human cases confirmed.', affectedPopulation: 45000, startDate: new Date('2026-03-01'), commanderName: 'Sunita Patel', estimatedDamage: 230000000 },
      { title: 'Colorado Flood Emergency', type: 'flood', severity: 3, status: 'resolved', location: 'Boulder, CO', latitude: 40.0150, longitude: -105.2705, description: 'Flash flooding from rapid snowmelt caused significant damage to Boulder and surrounding communities.', affectedPopulation: 55000, startDate: new Date('2026-02-20'), endDate: new Date('2026-03-05'), commanderName: 'Tom Anderson', estimatedDamage: 750000000 },
      { title: 'Oklahoma Tornado', type: 'tornado', severity: 3, status: 'resolved', location: 'Moore, OK', latitude: 35.3395, longitude: -97.4867, description: 'EF3 tornado struck Moore, Oklahoma causing significant residential damage.', affectedPopulation: 60000, startDate: new Date('2026-02-28'), endDate: new Date('2026-03-02'), commanderName: 'David Johnson', estimatedDamage: 420000000 },
      { title: 'Florida Hurricane Aftermath', type: 'hurricane', severity: 4, status: 'resolved', location: 'Fort Myers, FL', latitude: 26.6406, longitude: -81.8723, description: 'Recovery operations for Category 3 hurricane that devastated Fort Myers and Cape Coral.', affectedPopulation: 750000, startDate: new Date('2026-01-15'), endDate: new Date('2026-02-28'), commanderName: 'Lisa Garcia', estimatedDamage: 28000000000 },
      { title: 'Montana Wildfire Season', type: 'wildfire', severity: 2, status: 'closed', location: 'Missoula, MT', latitude: 46.8721, longitude: -113.9940, description: 'Seasonal wildfire activity in western Montana. All major fires now contained.', affectedPopulation: 12000, startDate: new Date('2025-08-15'), endDate: new Date('2025-10-30'), commanderName: 'James Thompson', estimatedDamage: 95000000 },
      { title: 'Northeast Winter Storm', type: 'flood', severity: 2, status: 'closed', location: 'Boston, MA', latitude: 42.3601, longitude: -71.0589, description: 'Major nor-easter caused coastal flooding and blizzard conditions across New England.', affectedPopulation: 200000, startDate: new Date('2026-01-20'), endDate: new Date('2026-01-25'), commanderName: 'Nancy Kim', estimatedDamage: 310000000 },
      { title: 'Texas Chemical Leak', type: 'chemical_spill', severity: 2, status: 'closed', location: 'Texas City, TX', latitude: 29.3838, longitude: -94.9027, description: 'Minor chemical leak at refinery. Contained within 12 hours with no injuries.', affectedPopulation: 8000, startDate: new Date('2026-02-14'), endDate: new Date('2026-02-14'), commanderName: 'Brian Smith', estimatedDamage: 15000000 },
      { title: 'Alaska Earthquake', type: 'earthquake', severity: 3, status: 'monitoring', location: 'Anchorage, AK', latitude: 61.2181, longitude: -149.9003, description: 'Magnitude 6.2 earthquake centered 30 miles north of Anchorage. Aftershocks continuing.', affectedPopulation: 290000, startDate: new Date('2026-03-12'), commanderName: 'Robert Wilson', estimatedDamage: 180000000 },
    ]);
    console.log('Incidents seeded.');

    // ===== RESOURCES =====
    await db.Resource.bulkCreate([
      { name: 'FEMA Mobile Command Unit Alpha', type: 'vehicle', status: 'deployed', quantity: 1, location: 'Houston, TX', assignedIncidentId: incidents[0].id, condition: 'Excellent', costPerUnit: 2500000, lastInspection: new Date('2026-02-01') },
      { name: 'Black Hawk Helicopter Fleet', type: 'aircraft', status: 'deployed', quantity: 4, location: 'Houston, TX', assignedIncidentId: incidents[0].id, condition: 'Good', costPerUnit: 21000000, lastInspection: new Date('2026-01-15') },
      { name: 'Search & Rescue Boats', type: 'boat', status: 'deployed', quantity: 12, location: 'Houston, TX', assignedIncidentId: incidents[0].id, condition: 'Good', costPerUnit: 85000, lastInspection: new Date('2026-02-20') },
      { name: 'National Guard Personnel Unit 7', type: 'personnel', status: 'deployed', quantity: 250, location: 'Paradise, CA', assignedIncidentId: incidents[1].id, condition: 'N/A', costPerUnit: 0, lastInspection: new Date('2026-03-01') },
      { name: 'Bulldozer Fleet - Heavy Equipment', type: 'equipment', status: 'deployed', quantity: 8, location: 'Paradise, CA', assignedIncidentId: incidents[1].id, condition: 'Good', costPerUnit: 450000, lastInspection: new Date('2026-01-10') },
      { name: 'Chinook CH-47 Transport Helicopters', type: 'aircraft', status: 'deployed', quantity: 2, location: 'Seattle, WA', assignedIncidentId: incidents[4].id, condition: 'Excellent', costPerUnit: 38000000, lastInspection: new Date('2026-02-15') },
      { name: 'Emergency Water Purification Units', type: 'equipment', status: 'deployed', quantity: 6, location: 'Memphis, TN', assignedIncidentId: incidents[3].id, condition: 'Good', costPerUnit: 125000, lastInspection: new Date('2026-01-20') },
      { name: 'Hazmat Response Vehicle', type: 'vehicle', status: 'deployed', quantity: 3, location: 'Baton Rouge, LA', assignedIncidentId: incidents[5].id, condition: 'Excellent', costPerUnit: 750000, lastInspection: new Date('2026-03-01') },
      { name: 'Urban Search & Rescue Equipment Cache', type: 'equipment', status: 'available', quantity: 15, location: 'FEMA Warehouse, Atlanta, GA', assignedIncidentId: null, condition: 'Excellent', costPerUnit: 35000, lastInspection: new Date('2026-02-28') },
      { name: 'Coast Guard Cutter', type: 'boat', status: 'deployed', quantity: 2, location: 'Honolulu, HI', assignedIncidentId: incidents[6].id, condition: 'Good', costPerUnit: 12000000, lastInspection: new Date('2026-01-05') },
      { name: 'Ambulance Fleet - Type I', type: 'vehicle', status: 'available', quantity: 20, location: 'FEMA Depot, Dallas, TX', assignedIncidentId: null, condition: 'Good', costPerUnit: 280000, lastInspection: new Date('2026-02-10') },
      { name: 'Portable Generator Units', type: 'equipment', status: 'available', quantity: 50, location: 'National Stockpile, Kansas City, MO', assignedIncidentId: null, condition: 'Good', costPerUnit: 15000, lastInspection: new Date('2026-01-30') },
      { name: 'MQ-9 Reaper Surveillance Drone', type: 'aircraft', status: 'deployed', quantity: 2, location: 'Joplin, MO', assignedIncidentId: incidents[2].id, condition: 'Excellent', costPerUnit: 16900000, lastInspection: new Date('2026-03-05') },
      { name: 'Inflatable Rescue Rafts', type: 'boat', status: 'available', quantity: 30, location: 'Regional Warehouse, Baton Rouge, LA', assignedIncidentId: null, condition: 'Good', costPerUnit: 5000, lastInspection: new Date('2026-02-15') },
      { name: 'Satellite Communication Trailer', type: 'vehicle', status: 'maintenance', quantity: 2, location: 'FEMA Region IV HQ, Atlanta, GA', assignedIncidentId: null, condition: 'Fair', costPerUnit: 350000, lastInspection: new Date('2025-12-01') },
    ]);
    console.log('Resources seeded.');

    // ===== SHELTERS =====
    await db.Shelter.bulkCreate([
      { name: 'George R. Brown Convention Center', address: '1001 Avenida De Las Americas, Houston, TX 77010', capacity: 10000, currentOccupancy: 7850, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'medical_station', 'charging_stations', 'pet_area', 'childcare'], contactPerson: 'Lisa Garcia', contactPhone: '713-555-0200', latitude: 29.7519, longitude: -95.3564 },
      { name: 'NRG Center', address: '1 NRG Park, Houston, TX 77054', capacity: 8000, currentOccupancy: 6200, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'medical_station', 'showers', 'laundry'], contactPerson: 'Maria Chen', contactPhone: '713-555-0201', latitude: 29.6847, longitude: -95.4107 },
      { name: 'Paradise Community Center', address: '5591 Black Olive Dr, Paradise, CA 95969', capacity: 500, currentOccupancy: 485, status: 'full', type: 'emergency', amenities: ['cots', 'food_service', 'first_aid'], contactPerson: 'Tom Anderson', contactPhone: '530-555-0202', latitude: 39.7596, longitude: -121.6219 },
      { name: 'Chico Fairgrounds Shelter', address: '199 E Hazel St, Chico, CA 95928', capacity: 2000, currentOccupancy: 1650, status: 'open', type: 'temporary', amenities: ['cots', 'food_service', 'medical_station', 'pet_area', 'showers'], contactPerson: 'Angela Wright', contactPhone: '530-555-0203', latitude: 39.7285, longitude: -121.8375 },
      { name: 'Joplin High School Gymnasium', address: '2104 Indiana Ave, Joplin, MO 64804', capacity: 1200, currentOccupancy: 890, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'first_aid', 'charging_stations'], contactPerson: 'David Johnson', contactPhone: '417-555-0204', latitude: 37.0842, longitude: -94.5133 },
      { name: 'Memphis Fairgrounds Emergency Shelter', address: '940 Early Maxwell Blvd, Memphis, TN 38104', capacity: 3000, currentOccupancy: 1200, status: 'open', type: 'temporary', amenities: ['cots', 'food_service', 'medical_station', 'showers', 'counseling'], contactPerson: 'Jennifer Rivera', contactPhone: '901-555-0205', latitude: 35.1350, longitude: -90.0255 },
      { name: 'Seattle Convention Center', address: '705 Pike St, Seattle, WA 98101', capacity: 5000, currentOccupancy: 4200, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'medical_station', 'charging_stations', 'pet_area', 'childcare', 'showers'], contactPerson: 'Karen Brown', contactPhone: '206-555-0206', latitude: 47.6117, longitude: -122.3316 },
      { name: 'Tacoma Dome', address: '2727 E D St, Tacoma, WA 98421', capacity: 6000, currentOccupancy: 3800, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'medical_station', 'showers', 'laundry', 'pet_area'], contactPerson: 'Nancy Kim', contactPhone: '253-555-0207', latitude: 47.2362, longitude: -122.4275 },
      { name: 'Baton Rouge Civic Center', address: '300 Convention St, Baton Rouge, LA 70801', capacity: 2500, currentOccupancy: 1900, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'decontamination', 'medical_station'], contactPerson: 'Brian Smith', contactPhone: '225-555-0208', latitude: 30.4488, longitude: -91.1872 },
      { name: 'Honolulu Community College', address: '874 Dillingham Blvd, Honolulu, HI 96817', capacity: 1500, currentOccupancy: 0, status: 'preparing', type: 'emergency', amenities: ['cots', 'food_service', 'first_aid'], contactPerson: 'Carlos Martin', contactPhone: '808-555-0209', latitude: 21.3225, longitude: -157.8641 },
      { name: 'Fort Myers Exhibition Hall', address: '2254 Edwards Dr, Fort Myers, FL 33901', capacity: 4000, currentOccupancy: 250, status: 'open', type: 'temporary', amenities: ['cots', 'food_service', 'medical_station', 'counseling', 'job_assistance'], contactPerson: 'Lisa Garcia', contactPhone: '239-555-0210', latitude: 26.6318, longitude: -81.8626 },
      { name: 'Des Moines Community Center', address: '200 Grand Ave, Des Moines, IA 50309', capacity: 800, currentOccupancy: 0, status: 'closed', type: 'emergency', amenities: ['cots', 'food_service', 'first_aid'], contactPerson: 'Sunita Patel', contactPhone: '515-555-0211', latitude: 41.5868, longitude: -93.6250 },
      { name: 'Moore Public School Complex', address: '400 SE 12th St, Moore, OK 73160', capacity: 1000, currentOccupancy: 0, status: 'closed', type: 'emergency', amenities: ['cots', 'food_service', 'first_aid', 'counseling'], contactPerson: 'David Johnson', contactPhone: '405-555-0212', latitude: 35.3395, longitude: -97.4867 },
      { name: 'Anchorage Sullivan Arena', address: '1600 Gambell St, Anchorage, AK 99501', capacity: 3500, currentOccupancy: 1100, status: 'open', type: 'emergency', amenities: ['cots', 'food_service', 'medical_station', 'heating', 'pet_area'], contactPerson: 'Robert Wilson', contactPhone: '907-555-0213', latitude: 61.2045, longitude: -149.8663 },
      { name: 'Boulder Valley YMCA', address: '2850 Mapleton Ave, Boulder, CO 80301', capacity: 600, currentOccupancy: 0, status: 'closed', type: 'temporary', amenities: ['cots', 'food_service', 'showers', 'counseling'], contactPerson: 'Tom Anderson', contactPhone: '303-555-0214', latitude: 40.0274, longitude: -105.2825 },
    ]);
    console.log('Shelters seeded.');

    // ===== VOLUNTEERS =====
    await db.Volunteer.bulkCreate([
      { name: 'Marcus Williams', email: 'mwilliams@redcross.org', phone: '713-555-0300', skills: ['first_aid', 'shelter_management', 'logistics'], availability: 'deployed', certifications: ['CPR', 'First Aid', 'FEMA ICS-100'], hoursLogged: 156, assignedIncidentId: incidents[0].id, location: 'Houston, TX', emergencyContact: 'Sarah Williams 713-555-0350' },
      { name: 'Emily Rodriguez', email: 'erodriguez@volunteer.org', phone: '530-555-0301', skills: ['medical', 'triage', 'counseling'], availability: 'deployed', certifications: ['EMT-B', 'Crisis Counseling', 'FEMA ICS-200'], hoursLogged: 89, assignedIncidentId: incidents[1].id, location: 'Chico, CA', emergencyContact: 'Juan Rodriguez 530-555-0351' },
      { name: 'Thomas Jackson', email: 'tjackson@civilair.org', phone: '417-555-0302', skills: ['search_rescue', 'communications', 'drone_operation'], availability: 'deployed', certifications: ['SAR Tech II', 'HAM Radio', 'FAA Part 107'], hoursLogged: 234, assignedIncidentId: incidents[2].id, location: 'Joplin, MO', emergencyContact: 'Linda Jackson 417-555-0352' },
      { name: 'Amanda Foster', email: 'afoster@medicorps.org', phone: '901-555-0303', skills: ['nursing', 'wound_care', 'pediatric_care'], availability: 'deployed', certifications: ['RN', 'PALS', 'ACLS'], hoursLogged: 178, assignedIncidentId: incidents[3].id, location: 'Memphis, TN', emergencyContact: 'Mark Foster 901-555-0353' },
      { name: 'Daniel Kim', email: 'dkim@teamrubicon.org', phone: '206-555-0304', skills: ['construction', 'heavy_equipment', 'demolition'], availability: 'deployed', certifications: ['OSHA 30', 'Heavy Equipment Operator', 'FEMA ICS-100'], hoursLogged: 312, assignedIncidentId: incidents[4].id, location: 'Seattle, WA', emergencyContact: 'Grace Kim 206-555-0354' },
      { name: 'Rachel Green', email: 'rgreen@salvation.org', phone: '225-555-0305', skills: ['food_service', 'logistics', 'distribution'], availability: 'deployed', certifications: ['ServSafe', 'Forklift Operator'], hoursLogged: 67, assignedIncidentId: incidents[5].id, location: 'Baton Rouge, LA', emergencyContact: 'Alan Green 225-555-0355' },
      { name: 'Christopher Nguyen', email: 'cnguyen@cert.gov', phone: '808-555-0306', skills: ['fire_suppression', 'light_search_rescue', 'first_aid'], availability: 'deployed', certifications: ['CERT', 'CPR', 'Fire Extinguisher'], hoursLogged: 45, assignedIncidentId: incidents[6].id, location: 'Honolulu, HI', emergencyContact: 'Mai Nguyen 808-555-0356' },
      { name: 'Jessica Taylor', email: 'jtaylor@redcross.org', phone: '515-555-0307', skills: ['shelter_management', 'data_entry', 'casework'], availability: 'available', certifications: ['Red Cross Shelter Ops', 'FEMA ICS-100'], hoursLogged: 423, assignedIncidentId: null, location: 'Des Moines, IA', emergencyContact: 'Mike Taylor 515-555-0357' },
      { name: 'Andrew Martinez', email: 'amartinez@volunteer.org', phone: '303-555-0308', skills: ['swift_water_rescue', 'boat_operation', 'diving'], availability: 'available', certifications: ['Swift Water Rescue Tech', 'USCG Boat Operator', 'PADI Divemaster'], hoursLogged: 567, assignedIncidentId: null, location: 'Denver, CO', emergencyContact: 'Rosa Martinez 303-555-0358' },
      { name: 'Sophia Adams', email: 'sadams@medicorps.org', phone: '405-555-0309', skills: ['mental_health', 'crisis_intervention', 'social_work'], availability: 'available', certifications: ['LCSW', 'Crisis Intervention', 'Psychological First Aid'], hoursLogged: 290, assignedIncidentId: null, location: 'Oklahoma City, OK', emergencyContact: 'John Adams 405-555-0359' },
      { name: 'William Chen', email: 'wchen@teamrubicon.org', phone: '907-555-0310', skills: ['medical', 'cold_weather_ops', 'mountaineering'], availability: 'deployed', certifications: ['Paramedic', 'Wilderness First Responder', 'Avalanche Level 2'], hoursLogged: 189, assignedIncidentId: incidents[14].id, location: 'Anchorage, AK', emergencyContact: 'Linda Chen 907-555-0360' },
      { name: 'Olivia Brown', email: 'obrown@redcross.org', phone: '617-555-0311', skills: ['communications', 'public_relations', 'translation_spanish'], availability: 'available', certifications: ['Red Cross PR', 'FEMA ICS-100'], hoursLogged: 134, assignedIncidentId: null, location: 'Boston, MA', emergencyContact: 'Peter Brown 617-555-0361' },
      { name: 'James Wilson', email: 'jwilson@cert.gov', phone: '239-555-0312', skills: ['damage_assessment', 'construction', 'electrical'], availability: 'deployed', certifications: ['Building Inspector', 'Licensed Electrician', 'FEMA IA'], hoursLogged: 256, assignedIncidentId: incidents[10].id, location: 'Fort Myers, FL', emergencyContact: 'Sarah Wilson 239-555-0362' },
      { name: 'Lauren Phillips', email: 'lphillips@volunteer.org', phone: '253-555-0313', skills: ['logistics', 'inventory_management', 'cdl_driver'], availability: 'deployed', certifications: ['CDL Class A', 'FEMA Logistics', 'Hazmat Endorsement'], hoursLogged: 198, assignedIncidentId: incidents[4].id, location: 'Tacoma, WA', emergencyContact: 'Dave Phillips 253-555-0363' },
      { name: 'Ryan O\'Brien', email: 'robrien@civilair.org', phone: '713-555-0314', skills: ['aviation', 'aerial_survey', 'photography'], availability: 'deployed', certifications: ['Commercial Pilot', 'FAA Part 107', 'Aerial Photography'], hoursLogged: 78, assignedIncidentId: incidents[0].id, location: 'Houston, TX', emergencyContact: 'Megan O\'Brien 713-555-0364' },
    ]);
    console.log('Volunteers seeded.');

    // ===== SUPPLIES =====
    await db.Supply.bulkCreate([
      { name: 'MRE Cases (Meals Ready to Eat)', category: 'food', quantity: 50000, unit: 'cases', location: 'FEMA Distribution Center, Houston, TX', expirationDate: new Date('2029-06-15'), status: 'in_stock', reorderLevel: 10000, supplier: 'Ameriqual Group LLC', cost: 89.50 },
      { name: 'Bottled Water (16.9oz)', category: 'water', quantity: 200000, unit: 'bottles', location: 'FEMA Distribution Center, Houston, TX', expirationDate: new Date('2028-12-31'), status: 'in_stock', reorderLevel: 50000, supplier: 'Nestle Waters', cost: 0.35 },
      { name: 'Emergency First Aid Kits', category: 'medical', quantity: 5000, unit: 'kits', location: 'Regional Medical Cache, Atlanta, GA', expirationDate: new Date('2027-09-30'), status: 'in_stock', reorderLevel: 1000, supplier: 'Johnson & Johnson', cost: 45.00 },
      { name: 'Emergency Blankets (Mylar)', category: 'clothing', quantity: 75000, unit: 'blankets', location: 'National Stockpile, Kansas City, MO', expirationDate: null, status: 'in_stock', reorderLevel: 15000, supplier: 'Swiss Safe Products', cost: 2.50 },
      { name: 'Emergency Shelter Tents (10-person)', category: 'shelter', quantity: 2000, unit: 'tents', location: 'FEMA Warehouse, Dallas, TX', expirationDate: null, status: 'in_stock', reorderLevel: 500, supplier: 'UNHCR Shelter Systems', cost: 850.00 },
      { name: 'Chainsaw - Professional Grade', category: 'tools', quantity: 300, unit: 'units', location: 'Equipment Depot, Joplin, MO', expirationDate: null, status: 'in_stock', reorderLevel: 50, supplier: 'Stihl Inc.', cost: 649.99 },
      { name: 'Diesel Fuel', category: 'fuel', quantity: 15000, unit: 'gallons', location: 'Fuel Depot, Houston, TX', expirationDate: new Date('2027-03-15'), status: 'low_stock', reorderLevel: 20000, supplier: 'Shell Oil Company', cost: 3.85 },
      { name: 'Prescription Medication Cache', category: 'medical', quantity: 10000, unit: 'units', location: 'CHEMPACK Storage, Seattle, WA', expirationDate: new Date('2027-06-30'), status: 'in_stock', reorderLevel: 2000, supplier: 'McKesson Corporation', cost: 12.50 },
      { name: 'Water Purification Tablets', category: 'water', quantity: 500000, unit: 'tablets', location: 'National Stockpile, Kansas City, MO', expirationDate: new Date('2030-01-01'), status: 'in_stock', reorderLevel: 100000, supplier: 'Katadyn Group', cost: 0.10 },
      { name: 'Canned Food Assortment', category: 'food', quantity: 30000, unit: 'cans', location: 'Salvation Army Warehouse, Memphis, TN', expirationDate: new Date('2028-04-15'), status: 'in_stock', reorderLevel: 5000, supplier: 'Feeding America', cost: 1.25 },
      { name: 'Infant Formula', category: 'food', quantity: 800, unit: 'cases', location: 'Red Cross Depot, Houston, TX', expirationDate: new Date('2027-01-31'), status: 'low_stock', reorderLevel: 1000, supplier: 'Abbott Nutrition', cost: 32.00 },
      { name: 'Personal Protective Equipment Kits', category: 'clothing', quantity: 25000, unit: 'kits', location: 'CDC Strategic National Stockpile', expirationDate: new Date('2028-08-15'), status: 'in_stock', reorderLevel: 5000, supplier: '3M Company', cost: 18.75 },
      { name: 'Plywood Sheets (4x8)', category: 'shelter', quantity: 5000, unit: 'sheets', location: 'Home Depot Distribution, Baton Rouge, LA', expirationDate: null, status: 'in_stock', reorderLevel: 1000, supplier: 'Georgia-Pacific', cost: 42.00 },
      { name: 'Portable Water Containers (5-gal)', category: 'water', quantity: 100, unit: 'containers', location: 'Paradise, CA Field Station', expirationDate: null, status: 'out_of_stock', reorderLevel: 500, supplier: 'Scepter Military', cost: 22.00 },
      { name: 'Gasoline', category: 'fuel', quantity: 8000, unit: 'gallons', location: 'Emergency Fuel Reserve, Seattle, WA', expirationDate: new Date('2026-09-15'), status: 'in_transit', reorderLevel: 10000, supplier: 'Chevron', cost: 4.25 },
    ]);
    console.log('Supplies seeded.');

    // ===== EVACUATIONS =====
    await db.Evacuation.bulkCreate([
      { zone: 'Zone A - Galveston Island', routeName: 'I-45 North Corridor', status: 'completed', priority: 'critical', estimatedPopulation: 50000, evacuatedCount: 48500, destination: 'George R. Brown Convention Center, Houston', startTime: new Date('2026-03-14T06:00:00'), endTime: new Date('2026-03-14T18:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Island evacuation completed before hurricane landfall. Contraflow activated on I-45.', incidentId: incidents[0].id },
      { zone: 'Zone B - Texas City Industrial', routeName: 'TX-146 to I-45', status: 'completed', priority: 'critical', estimatedPopulation: 75000, evacuatedCount: 71200, destination: 'NRG Center, Houston', startTime: new Date('2026-03-14T08:00:00'), endTime: new Date('2026-03-15T02:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Industrial zone evacuation. Chemical facilities secured before departure.', incidentId: incidents[0].id },
      { zone: 'Zone C - Clear Lake Area', routeName: 'I-45 North / SH-225', status: 'active', priority: 'high', estimatedPopulation: 120000, evacuatedCount: 95000, destination: 'Multiple shelters in North Houston', startTime: new Date('2026-03-15T06:00:00'), transportMode: 'Bus, Personal Vehicle, National Guard', notes: 'Ongoing evacuation. Some residents refusing to leave.', incidentId: incidents[0].id },
      { zone: 'Paradise Evacuation Zone', routeName: 'Skyway / Clark Road', status: 'completed', priority: 'critical', estimatedPopulation: 27000, evacuatedCount: 25800, destination: 'Chico Fairgrounds', startTime: new Date('2026-03-10T14:00:00'), endTime: new Date('2026-03-10T22:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Wildfire evacuation. Multiple road closures required rerouting.', incidentId: incidents[1].id },
      { zone: 'Joplin Downtown', routeName: 'I-44 East to Springfield', status: 'completed', priority: 'high', estimatedPopulation: 15000, evacuatedCount: 14200, destination: 'Springfield Convention Center', startTime: new Date('2026-03-14T16:00:00'), endTime: new Date('2026-03-14T20:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Post-tornado evacuation of damaged areas.', incidentId: incidents[2].id },
      { zone: 'Memphis Riverside District', routeName: 'I-40 East', status: 'active', priority: 'medium', estimatedPopulation: 35000, evacuatedCount: 22000, destination: 'Memphis Fairgrounds', startTime: new Date('2026-03-12T10:00:00'), transportMode: 'Bus, National Guard Trucks', notes: 'Flood evacuation. Water levels still rising.', incidentId: incidents[3].id },
      { zone: 'Seattle Waterfront District', routeName: 'I-5 North / SR-99', status: 'active', priority: 'critical', estimatedPopulation: 85000, evacuatedCount: 62000, destination: 'Seattle Convention Center / Tacoma Dome', startTime: new Date('2026-03-16T09:00:00'), transportMode: 'Bus, Light Rail, Ferry', notes: 'Earthquake evacuation. Multiple building collapses reported.', incidentId: incidents[4].id },
      { zone: 'Baton Rouge Chemical Zone - 5mi Radius', routeName: 'I-10 East and West', status: 'active', priority: 'critical', estimatedPopulation: 125000, evacuatedCount: 98000, destination: 'Baton Rouge Civic Center / LSU Campus', startTime: new Date('2026-03-17T06:00:00'), transportMode: 'Bus, Personal Vehicle, National Guard', notes: 'Chemical exposure evacuation. Wind direction shifting.', incidentId: incidents[5].id },
      { zone: 'Waikiki Beach to Diamond Head', routeName: 'H-1 Freeway North', status: 'planned', priority: 'high', estimatedPopulation: 45000, evacuatedCount: 0, destination: 'Honolulu Community College', startTime: new Date('2026-03-17T14:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Tsunami evacuation plan activated. Awaiting wave arrival confirmation.', incidentId: incidents[6].id },
      { zone: 'Pioneer Square - Seattle', routeName: 'I-90 East', status: 'active', priority: 'high', estimatedPopulation: 12000, evacuatedCount: 8500, destination: 'Bellevue Community Centers', startTime: new Date('2026-03-16T11:00:00'), transportMode: 'Bus, Walking', notes: 'Historic district evacuation. Many unreinforced masonry buildings collapsed.', incidentId: incidents[4].id },
      { zone: 'South Platte River Corridor', routeName: 'US-36 West to Boulder', status: 'completed', priority: 'medium', estimatedPopulation: 8000, evacuatedCount: 7800, destination: 'Boulder Valley YMCA', startTime: new Date('2026-02-21T08:00:00'), endTime: new Date('2026-02-21T16:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Flash flood evacuation completed successfully.', incidentId: incidents[8].id },
      { zone: 'Moore Residential Area', routeName: 'I-35 North to Norman', status: 'completed', priority: 'high', estimatedPopulation: 20000, evacuatedCount: 19500, destination: 'Moore Public School Complex', startTime: new Date('2026-02-28T14:30:00'), endTime: new Date('2026-02-28T18:00:00'), transportMode: 'Bus, Personal Vehicle', notes: 'Tornado warning evacuation. Swift community response.', incidentId: incidents[9].id },
      { zone: 'Fort Myers Beach', routeName: 'Estero Blvd to I-75', status: 'completed', priority: 'critical', estimatedPopulation: 6500, evacuatedCount: 5900, destination: 'Fort Myers Exhibition Hall', startTime: new Date('2026-01-14T06:00:00'), endTime: new Date('2026-01-14T14:00:00'), transportMode: 'Bus, Personal Vehicle, Boat', notes: 'Pre-hurricane evacuation of barrier island.', incidentId: incidents[10].id },
      { name: 'Anchorage Downtown', zone: 'Anchorage City Center', routeName: 'AK-1 Glenn Highway North', status: 'planned', priority: 'medium', estimatedPopulation: 30000, evacuatedCount: 0, destination: 'Anchorage Sullivan Arena', startTime: null, transportMode: 'Bus, Personal Vehicle', notes: 'Contingency plan in case of major aftershock. Monitoring.', incidentId: incidents[14].id },
      { zone: 'Des Moines Industrial Park', routeName: 'I-235 to I-80', status: 'cancelled', priority: 'low', estimatedPopulation: 5000, evacuatedCount: 0, destination: 'Des Moines Community Center', startTime: null, transportMode: 'Personal Vehicle', notes: 'Avian flu containment did not require civilian evacuation.', incidentId: incidents[7].id },
    ]);
    console.log('Evacuations seeded.');

    // ===== DAMAGE ASSESSMENTS =====
    await db.DamageAssessment.bulkCreate([
      { location: 'Galveston Island Seawall District', incidentId: incidents[0].id, assessorName: 'James Wilson', damageLevel: 'catastrophic', structuralDamage: 'Complete destruction of 60% of structures along the seawall. Storm surge overtopped the seawall by 8 feet.', infrastructureDamage: 'All roads impassable. Power grid destroyed. Water and sewer systems compromised.', estimatedCost: 8500000000, photosUrl: '/assessments/galveston-001', status: 'completed', recommendations: 'Area must remain closed. Full demolition of unsafe structures required before rebuild.', assessmentDate: new Date('2026-03-16') },
      { location: 'Texas City Refinery Complex', incidentId: incidents[0].id, assessorName: 'Brian Smith', damageLevel: 'severe', structuralDamage: 'Multiple storage tanks ruptured. Piping systems extensively damaged. Control rooms flooded.', infrastructureDamage: 'Rail lines washed out. Access roads covered in debris. Industrial water treatment offline.', estimatedCost: 4200000000, photosUrl: '/assessments/texascity-001', status: 'in_progress', recommendations: 'Environmental remediation priority. Containment booms deployed for oil/chemical runoff.', assessmentDate: new Date('2026-03-17') },
      { location: 'Paradise Town Center', incidentId: incidents[1].id, assessorName: 'Tom Anderson', damageLevel: 'catastrophic', structuralDamage: '90% of commercial structures destroyed by fire. Only concrete/masonry buildings partially standing.', infrastructureDamage: 'All utilities destroyed. Road surfaces melted in places. Cell towers destroyed.', estimatedCost: 1800000000, photosUrl: '/assessments/paradise-001', status: 'completed', recommendations: 'Complete rebuild required. Hazardous materials survey needed before clearing.', assessmentDate: new Date('2026-03-12') },
      { location: 'Joplin Medical Center District', incidentId: incidents[2].id, assessorName: 'Daniel Kim', damageLevel: 'severe', structuralDamage: 'Hospital sustained major roof damage. Parking structure collapsed. Adjacent clinic destroyed.', infrastructureDamage: 'Natural gas leaks reported. Power lines down across 12 blocks. Water main breaks.', estimatedCost: 950000000, photosUrl: '/assessments/joplin-001', status: 'completed', recommendations: 'Hospital must relocate operations. Gas line isolation required.', assessmentDate: new Date('2026-03-15') },
      { location: 'Memphis Riverside Drive', incidentId: incidents[3].id, assessorName: 'Amanda Foster', damageLevel: 'moderate', structuralDamage: 'First-floor flooding in 200+ commercial buildings. Some foundation undermining observed.', infrastructureDamage: 'Riverside road buckled. Storm drains overwhelmed. Electrical substations flooded.', estimatedCost: 320000000, photosUrl: '/assessments/memphis-001', status: 'in_progress', recommendations: 'Pump operations to continue. Building inspections required before reoccupancy.', assessmentDate: new Date('2026-03-14') },
      { location: 'Seattle Pioneer Square', incidentId: incidents[4].id, assessorName: 'Daniel Kim', damageLevel: 'catastrophic', structuralDamage: 'Multiple unreinforced masonry buildings collapsed. Historic structures severely cracked. Underground infrastructure exposed.', infrastructureDamage: 'Alaskan Way Viaduct replacement tunnel cracked. Water mains broken. Gas leaks widespread.', estimatedCost: 12000000000, photosUrl: '/assessments/seattle-001', status: 'in_progress', recommendations: 'Entire district must be cordoned off. Structural engineers needed for every building. Underground utility survey critical.', assessmentDate: new Date('2026-03-17') },
      { location: 'Seattle Capitol Hill', incidentId: incidents[4].id, assessorName: 'Lauren Phillips', damageLevel: 'moderate', structuralDamage: 'Chimney collapses on older homes. Cracked foundations in 15% of buildings surveyed.', infrastructureDamage: 'Water pressure drops. Some power outages. Road surface cracks on steep grades.', estimatedCost: 450000000, photosUrl: '/assessments/seattle-002', status: 'in_progress', recommendations: 'Red-tag inspections for older buildings. Water system pressure testing needed.', assessmentDate: new Date('2026-03-17') },
      { location: 'Baton Rouge Industrial Corridor', incidentId: incidents[5].id, assessorName: 'Brian Smith', damageLevel: 'severe', structuralDamage: 'Chemical plant primary structure destroyed. Adjacent facilities damaged by blast wave. Containment walls breached.', infrastructureDamage: 'Road surfaces buckled from heat. Railroad tracks warped. Underground pipelines require integrity testing.', estimatedCost: 890000000, photosUrl: '/assessments/batonrouge-001', status: 'in_progress', recommendations: 'Hazmat teams must complete decontamination before structural assessment can continue.', assessmentDate: new Date('2026-03-17') },
      { location: 'Boulder Creek Corridor', incidentId: incidents[8].id, assessorName: 'Tom Anderson', damageLevel: 'moderate', structuralDamage: 'Foundation damage to 45 homes along creek. Two pedestrian bridges washed out.', infrastructureDamage: 'Creek-side trail system destroyed. Storm drainage overwhelmed. One road bridge undermined.', estimatedCost: 125000000, photosUrl: '/assessments/boulder-001', status: 'completed', recommendations: 'Buyout program recommended for most flood-prone properties. Bridge replacement needed.', assessmentDate: new Date('2026-02-25') },
      { location: 'Moore Residential District', incidentId: incidents[9].id, assessorName: 'James Wilson', damageLevel: 'severe', structuralDamage: '340 homes destroyed, 520 homes with major damage. Two schools significantly damaged.', infrastructureDamage: 'Power lines down across 4 square miles. Water main breaks in 6 locations.', estimatedCost: 420000000, photosUrl: '/assessments/moore-001', status: 'completed', recommendations: 'Safe room retrofit program for rebuilt homes. Updated building codes recommended.', assessmentDate: new Date('2026-03-01') },
      { location: 'Fort Myers Beach Estero Island', incidentId: incidents[10].id, assessorName: 'Lisa Garcia', damageLevel: 'catastrophic', structuralDamage: '80% of structures destroyed or rendered uninhabitable. Concrete slab foundations scoured.', infrastructureDamage: 'Bridge to mainland damaged. All utilities destroyed. Beach erosion of 50+ feet.', estimatedCost: 6500000000, photosUrl: '/assessments/fortmyers-001', status: 'completed', recommendations: 'Island rebuilding plan with elevated construction standards. Utility infrastructure complete replacement.', assessmentDate: new Date('2026-01-25') },
      { location: 'Anchorage Midtown', incidentId: incidents[14].id, assessorName: 'William Chen', damageLevel: 'minor', structuralDamage: 'Cosmetic cracking in some buildings. A few facade panels dislodged.', infrastructureDamage: 'Minor road surface cracks. Traffic signals malfunctioning at 12 intersections.', estimatedCost: 25000000, photosUrl: '/assessments/anchorage-001', status: 'completed', recommendations: 'Routine inspections sufficient. Signal repair crews dispatched.', assessmentDate: new Date('2026-03-13') },
      { location: 'Tacoma Port Industrial Area', incidentId: incidents[4].id, assessorName: 'Lauren Phillips', damageLevel: 'moderate', structuralDamage: 'Crane damage at container terminal. Warehouse wall collapses. Pier surface cracking.', infrastructureDamage: 'Rail connections disrupted. Port access road damaged. Shoreline liquefaction observed.', estimatedCost: 780000000, photosUrl: '/assessments/tacoma-001', status: 'pending', recommendations: 'Geotechnical survey required. Crane safety inspections mandatory before port reopening.', assessmentDate: new Date('2026-03-18') },
      { location: 'Honolulu Waikiki Beach', incidentId: incidents[6].id, assessorName: 'Christopher Nguyen', damageLevel: 'minor', structuralDamage: 'No structural damage yet. Pre-event assessment documenting baseline conditions.', infrastructureDamage: 'All infrastructure operational. Emergency barriers being deployed.', estimatedCost: 0, photosUrl: '/assessments/honolulu-001', status: 'pending', recommendations: 'Continue monitoring. Post-event assessment required if tsunami impacts area.', assessmentDate: new Date('2026-03-17') },
      { location: 'Des Moines Agricultural District', incidentId: incidents[7].id, assessorName: 'Sunita Patel', damageLevel: 'moderate', structuralDamage: 'Poultry facility containment structures intact but contaminated. Requiring decontamination.', infrastructureDamage: 'No infrastructure damage. Biosecurity perimeters established on 15 farms.', estimatedCost: 230000000, photosUrl: '/assessments/desmoines-001', status: 'completed', recommendations: 'Depopulation of affected flocks. Enhanced biosecurity for 10-mile radius.', assessmentDate: new Date('2026-03-05') },
    ]);
    console.log('Damage Assessments seeded.');

    // ===== COMMUNICATIONS =====
    await db.Communication.bulkCreate([
      { type: 'alert', priority: 'critical', subject: 'HURRICANE ELENA - MANDATORY EVACUATION ORDER', message: 'Mandatory evacuation ordered for Galveston County and coastal Harris County. All residents must evacuate immediately via designated routes. Shelters open at George R. Brown Convention Center and NRG Center.', sender: 'Director Sarah Mitchell', recipients: ['all_houston_metro', 'galveston_county', 'harris_county'], channel: 'app', status: 'delivered', incidentId: incidents[0].id, timestamp: new Date('2026-03-14T05:00:00') },
      { type: 'broadcast', priority: 'critical', subject: 'EARTHQUAKE ALERT - SEATTLE METRO', message: 'Major earthquake 7.1M detected. Expect aftershocks. Move to open areas away from buildings. Do not use elevators. Check for gas leaks. If trapped, tap on pipes or walls.', sender: 'Director Sarah Mitchell', recipients: ['seattle_metro', 'tacoma', 'king_county'], channel: 'sms', status: 'delivered', incidentId: incidents[4].id, timestamp: new Date('2026-03-16T08:30:00') },
      { type: 'update', priority: 'high', subject: 'Wildfire Update - Paradise Evacuation Complete', message: 'Paradise evacuation is complete. 25,800 of 27,000 residents accounted for. Fire perimeter now at 65,000 acres and 15% contained. Air quality hazardous - N95 masks recommended within 30 miles.', sender: 'James Thompson', recipients: ['butte_county', 'cal_fire', 'fema_region_ix'], channel: 'email', status: 'delivered', incidentId: incidents[1].id, timestamp: new Date('2026-03-11T14:00:00') },
      { type: 'request', priority: 'high', subject: 'Request for Additional Medical Personnel - Joplin', message: 'Requesting 50 additional EMTs and 20 trauma surgeons for Joplin tornado response. Current medical capacity insufficient for casualty volume. Contact Regional Medical Coordinator Robert Wilson.', sender: 'Robert Wilson', recipients: ['fema_hq', 'hhs', 'national_guard_mo'], channel: 'satellite', status: 'read', incidentId: incidents[2].id, timestamp: new Date('2026-03-15T09:00:00') },
      { type: 'alert', priority: 'critical', subject: 'CHEMICAL RELEASE - SHELTER IN PLACE', message: 'Chlorine gas release detected in Baton Rouge industrial corridor. All residents within 5-mile radius must shelter in place. Close all windows and doors. Turn off HVAC systems. Await further instructions.', sender: 'Brian Smith', recipients: ['baton_rouge_metro', 'east_baton_rouge_parish'], channel: 'sms', status: 'delivered', incidentId: incidents[5].id, timestamp: new Date('2026-03-17T04:30:00') },
      { type: 'update', priority: 'medium', subject: 'Mississippi Flood Levels Update', message: 'River gauge at Memphis reads 42.3 feet, 7.3 feet above flood stage. Crest expected Thursday at 44 feet. Sandbagging operations continue along Riverside Drive. Additional volunteers needed.', sender: 'Maria Chen', recipients: ['memphis_eoc', 'shelby_county', 'army_corps_engineers'], channel: 'email', status: 'delivered', incidentId: incidents[3].id, timestamp: new Date('2026-03-13T16:00:00') },
      { type: 'broadcast', priority: 'high', subject: 'TSUNAMI WARNING - HAWAII', message: 'Tsunami warning in effect for all Hawaiian Islands. Expected wave arrival 1800 HST. Move to high ground immediately. Do not return to coastal areas until all-clear is issued.', sender: 'Karen Brown', recipients: ['hawaii_state', 'honolulu_county', 'maui_county', 'hawaii_county'], channel: 'app', status: 'delivered', incidentId: incidents[6].id, timestamp: new Date('2026-03-17T12:00:00') },
      { type: 'update', priority: 'medium', subject: 'Avian Flu Containment Progress', message: 'Containment zone expanded to 15 farms. All affected flocks being depopulated. 15 human cases confirmed, all with mild symptoms. Tamiflu distributed to exposed workers.', sender: 'Sunita Patel', recipients: ['cdc', 'usda', 'iowa_dept_health'], channel: 'email', status: 'read', incidentId: incidents[7].id, timestamp: new Date('2026-03-05T11:00:00') },
      { type: 'request', priority: 'critical', subject: 'Urgent: Heavy Lift Helicopter Needed - Seattle', message: 'Requesting CH-47 Chinook for hospital rooftop evacuation in Seattle. Harborview Medical Center has 200 patients requiring airlift. Ground routes blocked by debris.', sender: 'Daniel Kim', recipients: ['joint_base_lewis_mcchord', 'fema_region_x', 'washington_ng'], channel: 'radio', status: 'delivered', incidentId: incidents[4].id, timestamp: new Date('2026-03-16T10:15:00') },
      { type: 'update', priority: 'low', subject: 'Colorado Flood Recovery Progress Report', message: 'Recovery 85% complete in Boulder area. 7,500 of 7,800 evacuees returned home. FEMA individual assistance approved for 3,200 households. SBA disaster loans available.', sender: 'Tom Anderson', recipients: ['fema_region_viii', 'colorado_oem', 'boulder_county'], channel: 'email', status: 'read', incidentId: incidents[8].id, timestamp: new Date('2026-03-01T09:00:00') },
      { type: 'alert', priority: 'high', subject: 'Aftershock Warning - Anchorage', message: 'USGS reports increased aftershock probability. 40% chance of M5.0+ aftershock within 24 hours. Residents should be prepared for additional shaking. Inspect buildings for new damage.', sender: 'Robert Wilson', recipients: ['anchorage_municipality', 'alaska_dhs'], channel: 'app', status: 'delivered', incidentId: incidents[14].id, timestamp: new Date('2026-03-13T08:00:00') },
      { type: 'update', priority: 'medium', subject: 'Fort Myers Recovery - Housing Update', message: 'FEMA temporary housing units installed: 1,200 of 3,000 needed. Mobile home parks on Estero Island cleared for reconstruction. Building permit process expedited.', sender: 'Lisa Garcia', recipients: ['fema_region_iv', 'lee_county', 'fort_myers_city'], channel: 'email', status: 'delivered', incidentId: incidents[10].id, timestamp: new Date('2026-02-15T14:00:00') },
      { type: 'request', priority: 'medium', subject: 'Water Purification Equipment Request', message: 'Memphis water treatment plant operating at 40% capacity due to flooding. Requesting 10 portable water purification units for distribution points.', sender: 'Maria Chen', recipients: ['fema_logistics', 'army_corps_engineers'], channel: 'satellite', status: 'sent', incidentId: incidents[3].id, timestamp: new Date('2026-03-14T07:00:00') },
      { type: 'broadcast', priority: 'high', subject: 'Wildfire Air Quality Advisory', message: 'Air quality index exceeds 500 in Paradise and surrounding communities. All outdoor activities should cease. N95 masks mandatory for all personnel. Vulnerable populations should evacuate to clean air shelters.', sender: 'James Thompson', recipients: ['butte_county', 'tehama_county', 'glenn_county'], channel: 'app', status: 'delivered', incidentId: incidents[1].id, timestamp: new Date('2026-03-13T06:00:00') },
      { type: 'update', priority: 'low', subject: 'Moore Tornado - Final Recovery Status', message: 'All debris cleared. 95% of damaged homes repaired or rebuilt. New safe room construction program launched with 500 applications received. Case management services transitioning to long-term recovery group.', sender: 'David Johnson', recipients: ['fema_region_vi', 'oklahoma_oem', 'moore_city'], channel: 'email', status: 'read', incidentId: incidents[9].id, timestamp: new Date('2026-03-10T10:00:00') },
    ]);
    console.log('Communications seeded.');

    // ===== WEATHER ALERTS =====
    await db.WeatherAlert.bulkCreate([
      { type: 'hurricane', severity: 'emergency', region: 'Texas Gulf Coast', description: 'Hurricane Elena making landfall as Category 4. Catastrophic storm surge of 15-20 feet expected. Unsurvivable conditions near the eye.', startTime: new Date('2026-03-15T00:00:00'), endTime: new Date('2026-03-17T00:00:00'), source: 'National Hurricane Center', affectedAreas: ['Galveston', 'Houston', 'Texas City', 'Brazoria County', 'Chambers County'], windSpeed: 145, precipitation: 25, temperature: 78, recommendations: 'Evacuate immediately if in storm surge zone. Do not attempt to ride out the storm in mobile homes or flood-prone areas.' },
      { type: 'tornado', severity: 'warning', region: 'Southwest Missouri / Southeast Kansas', description: 'Tornado watch upgraded to warning. Multiple supercells producing tornadoes. Radar-confirmed EF4+ tornado moving NE at 45 mph.', startTime: new Date('2026-03-14T15:00:00'), endTime: new Date('2026-03-14T22:00:00'), source: 'NOAA Storm Prediction Center', affectedAreas: ['Joplin', 'Carthage', 'Webb City', 'Carl Junction'], windSpeed: 200, precipitation: 3, temperature: 72, recommendations: 'Take shelter immediately in interior room on lowest floor. Cover head and neck. Stay away from windows.' },
      { type: 'flood', severity: 'warning', region: 'Mississippi River Valley - Memphis', description: 'Major flood warning continues. Mississippi River to crest at 44 feet Thursday, 9 feet above flood stage. Record flooding expected.', startTime: new Date('2026-03-08T00:00:00'), endTime: new Date('2026-03-22T00:00:00'), source: 'National Weather Service Memphis', affectedAreas: ['Memphis', 'West Memphis', 'Tunica', 'Helena'], windSpeed: 15, precipitation: 8, temperature: 55, recommendations: 'Avoid flood waters. Turn around, don\'t drown. Monitor river gauge levels. Follow evacuation orders.' },
      { type: 'thunderstorm', severity: 'watch', region: 'Pacific Northwest', description: 'Strong thunderstorms possible in earthquake-affected areas. Concern for weakened structures. Lightning may trigger fires in damaged buildings with gas leaks.', startTime: new Date('2026-03-18T12:00:00'), endTime: new Date('2026-03-18T23:00:00'), source: 'NWS Seattle', affectedAreas: ['Seattle', 'Tacoma', 'Bellevue', 'Everett', 'Olympia'], windSpeed: 45, precipitation: 2, temperature: 48, recommendations: 'Secure loose debris from damaged buildings. Monitor for gas leaks during lightning. Seek shelter in structurally sound buildings only.' },
      { type: 'heat', severity: 'advisory', region: 'Central California', description: 'Excessive heat advisory for fire-affected areas. Temperatures 10-15 degrees above normal will hamper firefighting efforts and increase fire behavior.', startTime: new Date('2026-03-12T10:00:00'), endTime: new Date('2026-03-14T20:00:00'), source: 'NWS Sacramento', affectedAreas: ['Paradise', 'Chico', 'Oroville', 'Red Bluff'], windSpeed: 5, precipitation: 0, temperature: 98, recommendations: 'Stay hydrated. Firefighters should rotate frequently. Civilian residents should use cooling centers.' },
      { type: 'winter', severity: 'watch', region: 'Alaska - Southcentral', description: 'Winter storm watch for Anchorage and Matanuska-Susitna Valley. Heavy snow possible 12-18 inches. This will complicate earthquake recovery operations.', startTime: new Date('2026-03-19T00:00:00'), endTime: new Date('2026-03-20T18:00:00'), source: 'NWS Anchorage', affectedAreas: ['Anchorage', 'Wasilla', 'Palmer', 'Eagle River'], windSpeed: 35, precipitation: 18, temperature: 22, recommendations: 'Prepare for travel disruptions. Secure tarps over earthquake-damaged roofs. Stock up on fuel for generators.' },
      { type: 'hurricane', severity: 'watch', region: 'Hawaii', description: 'Tropical disturbance in central Pacific being monitored. May develop into tropical storm within 48 hours. Combined with tsunami threat, heightened alert status.', startTime: new Date('2026-03-19T00:00:00'), endTime: new Date('2026-03-22T00:00:00'), source: 'Central Pacific Hurricane Center', affectedAreas: ['Oahu', 'Maui', 'Big Island', 'Kauai'], windSpeed: 55, precipitation: 6, temperature: 82, recommendations: 'Monitor weather updates. Prepare hurricane kits. Review evacuation routes.' },
      { type: 'flood', severity: 'advisory', region: 'Lower Mississippi Valley', description: 'Flood advisory continues for areas downstream of Memphis. Moderate flooding expected in Vicksburg and Natchez areas as crest moves south.', startTime: new Date('2026-03-15T00:00:00'), endTime: new Date('2026-03-25T00:00:00'), source: 'NWS Jackson', affectedAreas: ['Vicksburg', 'Natchez', 'Greenville', 'Yazoo City'], windSpeed: 10, precipitation: 4, temperature: 62, recommendations: 'Stay informed. Protect valuables. Have evacuation plan ready.' },
      { type: 'thunderstorm', severity: 'warning', region: 'Texas Gulf Coast - Post Hurricane', description: 'Outer rain bands from Hurricane Elena producing severe thunderstorms with embedded tornadoes. Tornado warning for Harris County.', startTime: new Date('2026-03-15T14:00:00'), endTime: new Date('2026-03-15T20:00:00'), source: 'NWS Houston', affectedAreas: ['Houston', 'Katy', 'Sugar Land', 'Pasadena'], windSpeed: 85, precipitation: 6, temperature: 75, recommendations: 'Seek shelter immediately. Do not seek shelter in damaged structures. Use vehicles as last resort.' },
      { type: 'tornado', severity: 'watch', region: 'Oklahoma - Central', description: 'Tornado watch issued for central Oklahoma. Atmospheric conditions favorable for supercell development this afternoon and evening.', startTime: new Date('2026-03-18T14:00:00'), endTime: new Date('2026-03-18T23:00:00'), source: 'NOAA SPC', affectedAreas: ['Oklahoma City', 'Norman', 'Edmond', 'Moore', 'Midwest City'], windSpeed: 60, precipitation: 2, temperature: 76, recommendations: 'Review severe weather plan. Identify nearest shelter. Charge devices for weather alerts.' },
      { type: 'heat', severity: 'warning', region: 'Southern California', description: 'Dangerous heat wave expected. Record-breaking temperatures with offshore winds creating extreme fire weather conditions.', startTime: new Date('2026-03-18T08:00:00'), endTime: new Date('2026-03-21T20:00:00'), source: 'NWS Los Angeles', affectedAreas: ['Los Angeles', 'San Bernardino', 'Riverside', 'Ventura'], windSpeed: 40, precipitation: 0, temperature: 112, recommendations: 'Extreme fire danger. Red flag warning in effect. Stay indoors during peak heat. Check on elderly neighbors.' },
      { type: 'winter', severity: 'advisory', region: 'Northeast - New England', description: 'Winter weather advisory. Mixed precipitation expected with 2-4 inches of sleet and freezing rain making travel hazardous.', startTime: new Date('2026-03-18T22:00:00'), endTime: new Date('2026-03-19T12:00:00'), source: 'NWS Boston', affectedAreas: ['Boston', 'Providence', 'Hartford', 'Worcester'], windSpeed: 25, precipitation: 4, temperature: 30, recommendations: 'Avoid unnecessary travel. Treat walkways with salt. Power outages possible from ice accumulation.' },
      { type: 'flood', severity: 'warning', region: 'Iowa - Des Moines Metro', description: 'Flash flood warning for Des Moines River basin. Heavy rains upstream causing rapid rise. Agricultural areas at risk.', startTime: new Date('2026-03-17T06:00:00'), endTime: new Date('2026-03-18T18:00:00'), source: 'NWS Des Moines', affectedAreas: ['Des Moines', 'Ames', 'Ankeny', 'West Des Moines'], windSpeed: 20, precipitation: 5, temperature: 45, recommendations: 'Monitor local streams and rivers. Avoid driving through flooded roads. Protect livestock.' },
      { type: 'thunderstorm', severity: 'advisory', region: 'Gulf Coast - Louisiana', description: 'Thunderstorm advisory for Baton Rouge area. Storms may disperse chemical plume from industrial incident. Wind shifts possible.', startTime: new Date('2026-03-17T15:00:00'), endTime: new Date('2026-03-17T21:00:00'), source: 'NWS New Orleans', affectedAreas: ['Baton Rouge', 'Gonzales', 'Denham Springs', 'Port Allen'], windSpeed: 40, precipitation: 2, temperature: 80, recommendations: 'Chemical plume may shift with storms. Monitor wind direction. Be ready to shelter in place or evacuate depending on plume movement.' },
      { type: 'hurricane', severity: 'advisory', region: 'Atlantic Basin', description: 'Tropical depression forming in Caribbean. Models show possible Gulf Coast track within 7 days. Monitoring for potential compound disaster scenario.', startTime: new Date('2026-03-20T00:00:00'), endTime: new Date('2026-03-27T00:00:00'), source: 'National Hurricane Center', affectedAreas: ['Gulf Coast States', 'Caribbean Islands'], windSpeed: 35, precipitation: 3, temperature: 84, recommendations: 'Begin preparation activities. Review hurricane supplies. Monitor NHC updates every 6 hours.' },
    ]);
    console.log('Weather Alerts seeded.');

    // ===== DONATIONS =====
    await db.Donation.bulkCreate([
      { donorName: 'Walmart Foundation', donorEmail: 'giving@walmart.com', type: 'monetary', amount: 5000000, currency: 'USD', itemDescription: null, status: 'received', receivedDate: new Date('2026-03-15'), distributedDate: null, taxReceiptSent: true, notes: 'Designated for Hurricane Elena relief in Houston area.' },
      { donorName: 'American Red Cross Blood Drive', donorEmail: 'blood@redcross.org', type: 'supplies', amount: null, currency: 'USD', itemDescription: '2,500 units of O-negative blood and 1,800 units of O-positive blood', status: 'distributed', receivedDate: new Date('2026-03-16'), distributedDate: new Date('2026-03-17'), taxReceiptSent: false, notes: 'Emergency blood supply for Seattle earthquake casualties.' },
      { donorName: 'Jeff & MacKenzie Bezos Foundation', donorEmail: 'foundation@bezos.org', type: 'monetary', amount: 10000000, currency: 'USD', itemDescription: null, status: 'received', receivedDate: new Date('2026-03-16'), distributedDate: null, taxReceiptSent: true, notes: 'Pacific Northwest earthquake recovery fund.' },
      { donorName: 'Home Depot', donorEmail: 'corporate@homedepot.com', type: 'supplies', amount: 500000, currency: 'USD', itemDescription: '10,000 tarps, 5,000 plywood sheets, 2,000 generators, 50,000 batteries', status: 'received', receivedDate: new Date('2026-03-15'), distributedDate: null, taxReceiptSent: true, notes: 'Building materials for multiple disaster sites.' },
      { donorName: 'United Methodist Committee on Relief', donorEmail: 'umcor@umc.org', type: 'services', amount: 250000, currency: 'USD', itemDescription: 'Volunteer coordination for 500 trained disaster response volunteers', status: 'received', receivedDate: new Date('2026-03-14'), distributedDate: null, taxReceiptSent: true, notes: 'Volunteers deployed to Joplin tornado and Houston hurricane sites.' },
      { donorName: 'Anonymous Donor', donorEmail: null, type: 'monetary', amount: 1000000, currency: 'USD', itemDescription: null, status: 'received', receivedDate: new Date('2026-03-16'), distributedDate: null, taxReceiptSent: false, notes: 'General disaster relief fund. No designation specified.' },
      { donorName: 'PepsiCo Foundation', donorEmail: 'foundation@pepsico.com', type: 'supplies', amount: 300000, currency: 'USD', itemDescription: '500,000 bottles of water, 100,000 Gatorade bottles', status: 'distributed', receivedDate: new Date('2026-03-14'), distributedDate: new Date('2026-03-15'), taxReceiptSent: true, notes: 'Distributed to Houston shelters and Memphis flood relief.' },
      { donorName: 'Silicon Valley Community Foundation', donorEmail: 'grants@siliconvalleycf.org', type: 'monetary', amount: 2500000, currency: 'USD', itemDescription: null, status: 'pledged', receivedDate: null, distributedDate: null, taxReceiptSent: false, notes: 'Pledge for California wildfire recovery. Funds expected within 30 days.' },
      { donorName: 'Doctors Without Borders USA', donorEmail: 'usa@msf.org', type: 'services', amount: 750000, currency: 'USD', itemDescription: 'Mobile surgical unit with 12 surgeons and 30 nurses for 30-day deployment', status: 'received', receivedDate: new Date('2026-03-16'), distributedDate: null, taxReceiptSent: true, notes: 'Deployed to Seattle earthquake zone.' },
      { donorName: 'Anheuser-Busch', donorEmail: 'community@ab-inbev.com', type: 'supplies', amount: 150000, currency: 'USD', itemDescription: '300,000 cans of emergency drinking water', status: 'distributed', receivedDate: new Date('2026-03-15'), distributedDate: new Date('2026-03-16'), taxReceiptSent: true, notes: 'Emergency water shipped from Fort Collins brewery to Houston.' },
      { donorName: 'Amazon Web Services', donorEmail: 'disaster-response@amazon.com', type: 'services', amount: 500000, currency: 'USD', itemDescription: 'Cloud computing credits, satellite internet devices, logistics support', status: 'received', receivedDate: new Date('2026-03-16'), distributedDate: null, taxReceiptSent: true, notes: 'Technology support for communications restoration in earthquake zone.' },
      { donorName: 'Southern Baptist Convention Disaster Relief', donorEmail: 'disaster@sbc.net', type: 'services', amount: 180000, currency: 'USD', itemDescription: '20 mobile kitchen units serving 250,000 meals per day', status: 'distributed', receivedDate: new Date('2026-03-15'), distributedDate: new Date('2026-03-15'), taxReceiptSent: true, notes: 'Kitchen units deployed to Houston, Joplin, and Seattle shelters.' },
      { donorName: 'GoFundMe Community Campaign', donorEmail: 'campaigns@gofundme.com', type: 'monetary', amount: 8500000, currency: 'USD', itemDescription: null, status: 'received', receivedDate: new Date('2026-03-17'), distributedDate: null, taxReceiptSent: false, notes: 'Aggregated from 125,000 individual donors across multiple campaigns.' },
      { donorName: 'CVS Health Foundation', donorEmail: 'foundation@cvs.com', type: 'supplies', amount: 400000, currency: 'USD', itemDescription: 'Prescription medications, OTC medicines, first aid supplies, baby formula', status: 'received', receivedDate: new Date('2026-03-16'), distributedDate: null, taxReceiptSent: true, notes: 'Medical supplies for all active disaster sites.' },
      { donorName: 'IKEA Foundation', donorEmail: 'foundation@ikea.com', type: 'supplies', amount: 600000, currency: 'USD', itemDescription: '5,000 flat-pack temporary shelter units, 10,000 solar lanterns, 20,000 blankets', status: 'pledged', receivedDate: null, distributedDate: null, taxReceiptSent: false, notes: 'Shipping from European warehouses. ETA 10 days.' },
    ]);
    console.log('Donations seeded.');

    // ===== MEDICAL RESOURCES =====
    await db.MedicalResource.bulkCreate([
      { name: 'Type I Ambulance Unit Alpha', type: 'ambulance', quantity: 8, location: 'Houston, TX', status: 'in_use', assignedIncidentId: incidents[0].id, expirationDate: null, certificationRequired: 'EMT-B minimum', supplier: 'American Medical Response' },
      { name: 'ICU Hospital Beds - Methodist Hospital', type: 'hospital_bed', quantity: 45, location: 'Houston, TX', status: 'in_use', assignedIncidentId: incidents[0].id, expirationDate: null, certificationRequired: 'RN', supplier: 'Houston Methodist' },
      { name: 'Portable Ventilator Units', type: 'ventilator', quantity: 30, location: 'Seattle, WA', status: 'in_use', assignedIncidentId: incidents[4].id, expirationDate: null, certificationRequired: 'Respiratory Therapist', supplier: 'Medtronic' },
      { name: 'O-Negative Blood Supply', type: 'blood_supply', quantity: 500, location: 'Joplin, MO', status: 'in_use', assignedIncidentId: incidents[2].id, expirationDate: new Date('2026-04-14'), certificationRequired: 'Phlebotomist', supplier: 'American Red Cross' },
      { name: 'Amoxicillin 500mg Cache', type: 'medication', quantity: 10000, location: 'FEMA Medical Cache, Atlanta, GA', status: 'available', assignedIncidentId: null, expirationDate: new Date('2027-08-15'), certificationRequired: 'MD/DO/PA/NP', supplier: 'McKesson Corporation' },
      { name: 'N95 Respirator Masks', type: 'ppe', quantity: 100000, location: 'CDC Strategic National Stockpile', status: 'available', assignedIncidentId: null, expirationDate: new Date('2028-12-31'), certificationRequired: 'Fit test required', supplier: '3M Company' },
      { name: 'Trauma First Aid Kits', type: 'first_aid', quantity: 5000, location: 'National Stockpile, Kansas City, MO', status: 'available', assignedIncidentId: null, expirationDate: new Date('2027-06-30'), certificationRequired: 'First Aid certified', supplier: 'North American Rescue' },
      { name: 'Mobile Surgical Unit', type: 'hospital_bed', quantity: 2, location: 'Seattle, WA', status: 'in_use', assignedIncidentId: incidents[4].id, expirationDate: null, certificationRequired: 'Board Certified Surgeon', supplier: 'Doctors Without Borders' },
      { name: 'ALS Ambulance Fleet', type: 'ambulance', quantity: 12, location: 'Memphis, TN', status: 'in_use', assignedIncidentId: incidents[3].id, expirationDate: null, certificationRequired: 'Paramedic', supplier: 'Memphis Fire Department' },
      { name: 'Tyvek Hazmat Suits Level A', type: 'ppe', quantity: 500, location: 'Baton Rouge, LA', status: 'in_use', assignedIncidentId: incidents[5].id, expirationDate: new Date('2028-03-15'), certificationRequired: 'HAZWOPER 40-hour', supplier: 'DuPont' },
      { name: 'Epinephrine Auto-Injectors', type: 'medication', quantity: 2000, location: 'Regional Pharmacy, Denver, CO', status: 'available', assignedIncidentId: null, expirationDate: new Date('2027-01-31'), certificationRequired: 'EMT-B minimum', supplier: 'Mylan Pharmaceuticals' },
      { name: 'Burn Treatment Kits', type: 'first_aid', quantity: 1000, location: 'Paradise, CA', status: 'in_use', assignedIncidentId: incidents[1].id, expirationDate: new Date('2027-09-30'), certificationRequired: 'EMT-B minimum', supplier: 'Safeguard Medical' },
      { name: 'Portable Defibrillator Units', type: 'first_aid', quantity: 75, location: 'Multiple Locations', status: 'available', assignedIncidentId: null, expirationDate: null, certificationRequired: 'BLS certified', supplier: 'Philips Healthcare' },
      { name: 'IV Fluid Supply - Normal Saline', type: 'medication', quantity: 8000, location: 'Houston, TX', status: 'in_use', assignedIncidentId: incidents[0].id, expirationDate: new Date('2028-05-15'), certificationRequired: 'RN/Paramedic', supplier: 'Baxter International' },
      { name: 'Field Hospital Tent System', type: 'hospital_bed', quantity: 3, location: 'Honolulu, HI', status: 'available', assignedIncidentId: incidents[6].id, expirationDate: null, certificationRequired: 'Medical Director oversight', supplier: 'US Army Medical Command' },
    ]);
    console.log('Medical Resources seeded.');

    // ===== SEARCH & RESCUE =====
    await db.SearchRescue.bulkCreate([
      { operationName: 'Operation Gulf Rescue', incidentId: incidents[0].id, teamLeader: 'Captain Mike Reynolds', teamSize: 45, searchArea: 'Galveston Island residential zones', status: 'active', personsFound: 127, personsRescued: 118, startTime: new Date('2026-03-15T12:00:00'), endTime: null, equipment: ['boats', 'helicopters', 'thermal_imaging', 'k9_units', 'chainsaws', 'jaws_of_life'], hazards: 'Flood waters contaminated with chemicals and sewage. Downed power lines. Structural collapse risk.', notes: 'Multiple swift water rescues completed. Night operations ongoing with infrared cameras.' },
      { operationName: 'Operation Phoenix Search', incidentId: incidents[1].id, teamLeader: 'Lieutenant Sarah Kowalski', teamSize: 30, searchArea: 'Paradise residential neighborhoods - Sectors A through F', status: 'active', personsFound: 15, personsRescued: 12, startTime: new Date('2026-03-11T06:00:00'), endTime: null, equipment: ['k9_units', 'drones', 'thermal_imaging', 'atv', 'protective_gear'], hazards: 'Active fire zones. Toxic smoke. Unstable structures. Hot spots.', notes: 'Three persons still unaccounted for. Cadaver dogs deployed in heavily burned areas.' },
      { operationName: 'Operation Twister Response', incidentId: incidents[2].id, teamLeader: 'Sergeant Bill Harper', teamSize: 60, searchArea: 'Joplin - 4 square mile tornado damage path', status: 'active', personsFound: 89, personsRescued: 82, startTime: new Date('2026-03-14T17:30:00'), endTime: null, equipment: ['heavy_equipment', 'listening_devices', 'k9_units', 'cranes', 'cameras', 'concrete_cutters'], hazards: 'Unstable rubble piles. Gas leaks. Exposed rebar and glass. Asbestos in older buildings.', notes: 'Grid search 75% complete. Focus shifting to collapsed commercial structures.' },
      { operationName: 'Operation Cascadia Rescue', incidentId: incidents[4].id, teamLeader: 'Commander Jennifer Tanaka', teamSize: 120, searchArea: 'Seattle Downtown and Pioneer Square - 15 collapsed buildings', status: 'active', personsFound: 234, personsRescued: 198, startTime: new Date('2026-03-16T09:00:00'), endTime: null, equipment: ['heavy_equipment', 'listening_devices', 'k9_units', 'cranes', 'cameras', 'concrete_cutters', 'drones', 'thermal_imaging'], hazards: 'Aftershocks. Building collapse risk. Gas leaks. Underground voids. Tsunami risk.', notes: 'International USAR teams from Canada and Japan en route. 36 persons still trapped in Cascade Tower collapse.' },
      { operationName: 'Operation River Watch', incidentId: incidents[3].id, teamLeader: 'Chief Randy Patterson', teamSize: 25, searchArea: 'Mississippi River levee breach areas - Tunica to Memphis', status: 'active', personsFound: 45, personsRescued: 45, startTime: new Date('2026-03-12T08:00:00'), endTime: null, equipment: ['boats', 'helicopters', 'drones', 'life_jackets', 'throw_ropes'], hazards: 'Fast-moving flood waters. Submerged obstacles. Hypothermia risk. Contaminated water.', notes: 'All located persons successfully rescued. Continuing to search isolated farmsteads.' },
      { operationName: 'Operation Chemical Shield', incidentId: incidents[5].id, teamLeader: 'Hazmat Chief Roberto Diaz', teamSize: 35, searchArea: 'Baton Rouge Industrial Corridor - 2 mile radius from blast site', status: 'active', personsFound: 28, personsRescued: 25, startTime: new Date('2026-03-17T05:00:00'), endTime: null, equipment: ['hazmat_suits', 'scba', 'chemical_detectors', 'decon_stations', 'ambulances'], hazards: 'Chlorine gas. Secondary explosion risk. Structural instability from blast damage.', notes: 'Three workers still unaccounted for near blast epicenter. Toxic atmosphere prevents close approach.' },
      { operationName: 'Operation Anchorage Aftershock', incidentId: incidents[14].id, teamLeader: 'Captain Erik Sorenson', teamSize: 20, searchArea: 'Anchorage - Government Hill and Ship Creek area', status: 'active', personsFound: 8, personsRescued: 8, startTime: new Date('2026-03-12T14:00:00'), endTime: null, equipment: ['thermal_imaging', 'listening_devices', 'k9_units', 'cold_weather_gear'], hazards: 'Aftershocks. Cold temperatures. Frozen ground complicating excavation. Short daylight hours.', notes: 'All trapped persons recovered. Transitioning to damage assessment phase.' },
      { operationName: 'Operation Island Hope', incidentId: incidents[6].id, teamLeader: 'Lieutenant Commander Kai Nakamura', teamSize: 40, searchArea: 'Oahu coastline - Waikiki to North Shore', status: 'planning', personsFound: 0, personsRescued: 0, startTime: null, endTime: null, equipment: ['boats', 'helicopters', 'jet_skis', 'life_jackets', 'drones'], hazards: 'Tsunami waves. Strong currents. Debris in water. Coral reef hazards.', notes: 'Pre-positioned for post-tsunami search operations if waves impact coastline.' },
      { operationName: 'Operation Boulder Recovery', incidentId: incidents[8].id, teamLeader: 'Sergeant Maria Gonzalez', teamSize: 15, searchArea: 'Boulder Creek area - 3 mile stretch', status: 'completed', personsFound: 12, personsRescued: 12, startTime: new Date('2026-02-21T06:00:00'), endTime: new Date('2026-02-23T18:00:00'), equipment: ['boats', 'swift_water_gear', 'k9_units', 'drones'], hazards: 'Swift water. Cold temperatures. Debris-laden flood waters.', notes: 'All missing persons found alive. Swift water teams performed 8 technical rescues.' },
      { operationName: 'Operation Moore Shield', incidentId: incidents[9].id, teamLeader: 'Chief Frank Novak', teamSize: 50, searchArea: 'Moore - EF3 tornado damage path', status: 'completed', personsFound: 67, personsRescued: 64, startTime: new Date('2026-02-28T15:00:00'), endTime: new Date('2026-03-01T22:00:00'), equipment: ['heavy_equipment', 'k9_units', 'listening_devices', 'chainsaws', 'cameras'], hazards: 'Gas leaks. Downed power lines. Unstable structures. Glass and debris.', notes: 'Search completed. Three fatalities confirmed. All other missing persons accounted for.' },
      { operationName: 'Operation Fort Myers Beach', incidentId: incidents[10].id, teamLeader: 'Commander Rick Stanton', teamSize: 75, searchArea: 'Fort Myers Beach - Estero Island complete', status: 'completed', personsFound: 156, personsRescued: 142, startTime: new Date('2026-01-16T06:00:00'), endTime: new Date('2026-01-22T18:00:00'), equipment: ['boats', 'helicopters', 'k9_units', 'heavy_equipment', 'drones', 'sonar'], hazards: 'Storm surge debris. Contaminated water. Structural collapse. Hazardous materials.', notes: 'Island search complete. 14 fatalities confirmed. All missing persons accounted for.' },
      { operationName: 'Operation Houston Heights', incidentId: incidents[0].id, teamLeader: 'Lieutenant Ana Reyes', teamSize: 30, searchArea: 'Houston Heights - flooded residential areas', status: 'active', personsFound: 89, personsRescued: 89, startTime: new Date('2026-03-16T06:00:00'), endTime: null, equipment: ['boats', 'jet_skis', 'drones', 'megaphones', 'life_jackets'], hazards: 'Flood waters rising. Fire ants. Snakes. Contaminated water.', notes: 'Door-to-door searches in flooded neighborhoods. Many elderly residents refusing to evacuate.' },
      { operationName: 'Operation Chico Perimeter', incidentId: incidents[1].id, teamLeader: 'Captain Derek Morrison', teamSize: 20, searchArea: 'Wildfire perimeter - Highway 70 to Highway 191', status: 'suspended', personsFound: 3, personsRescued: 2, startTime: new Date('2026-03-12T08:00:00'), endTime: null, equipment: ['fire_shelters', 'atv', 'radio', 'gps', 'water_packs'], hazards: 'Active fire. Extreme heat. Falling trees. Poor visibility from smoke.', notes: 'Search suspended due to fire activity. Will resume when conditions allow safe access.' },
      { operationName: 'Operation Sound Search', incidentId: incidents[4].id, teamLeader: 'Chief Petty Officer James Cook', teamSize: 15, searchArea: 'Puget Sound waterfront - piers and marina areas', status: 'active', personsFound: 12, personsRescued: 10, startTime: new Date('2026-03-16T14:00:00'), endTime: null, equipment: ['boats', 'divers', 'sonar', 'underwater_cameras', 'pontoons'], hazards: 'Cold water. Strong currents. Debris. Structural hazards from damaged piers.', notes: 'Two persons recovered from collapsed pier structure. Dive operations continue.' },
      { operationName: 'Operation Iowa Farm Watch', incidentId: incidents[7].id, teamLeader: 'Agent Sarah Hennings', teamSize: 10, searchArea: 'Affected poultry farms - 15 farm radius', status: 'completed', personsFound: 0, personsRescued: 0, startTime: new Date('2026-03-02T08:00:00'), endTime: new Date('2026-03-04T17:00:00'), equipment: ['ppe', 'decon_stations', 'sample_kits', 'biosecurity_equipment'], hazards: 'H5N1 exposure risk. Biosecurity protocols required.', notes: 'Not a traditional SAR operation. Focused on identifying exposed workers and ensuring all personnel accounted for on affected farms.' },
    ]);
    console.log('Search & Rescue operations seeded.');

    // ===== INFRASTRUCTURE =====
    await db.Infrastructure.bulkCreate([
      { name: 'Galveston Causeway (I-45)', type: 'bridge', status: 'damaged', location: 'Galveston, TX', lastInspected: new Date('2026-03-16'), damageLevel: 'severe', repairEstimate: 180000000, priority: 'critical', notes: 'Storm surge undermined bridge supports. Closed to all traffic. Emergency repairs prioritized.', incidentId: incidents[0].id },
      { name: 'Houston Power Grid - South Sector', type: 'power_grid', status: 'destroyed', location: 'Houston, TX', lastInspected: new Date('2026-03-16'), damageLevel: 'destroyed', repairEstimate: 450000000, priority: 'critical', notes: '75% of transmission lines down. 1.2 million customers without power. Estimated 3 weeks for full restoration.', incidentId: incidents[0].id },
      { name: 'Paradise Municipal Water System', type: 'water_system', status: 'destroyed', location: 'Paradise, CA', lastInspected: new Date('2026-03-12'), damageLevel: 'destroyed', repairEstimate: 85000000, priority: 'high', notes: 'All water infrastructure melted or contaminated. Temporary water distribution established.', incidentId: incidents[1].id },
      { name: 'Joplin St. Johns Regional Medical Center', type: 'hospital', status: 'destroyed', location: 'Joplin, MO', lastInspected: new Date('2026-03-15'), damageLevel: 'destroyed', repairEstimate: 500000000, priority: 'critical', notes: 'Direct hit by EF4 tornado. Complete structural failure. Temporary field hospital established.', incidentId: incidents[2].id },
      { name: 'Memphis I-40 River Bridge', type: 'bridge', status: 'damaged', location: 'Memphis, TN', lastInspected: new Date('2026-03-13'), damageLevel: 'moderate', repairEstimate: 45000000, priority: 'high', notes: 'Flood scour around bridge piers detected. Weight restrictions in place. Engineers monitoring.', incidentId: incidents[3].id },
      { name: 'Seattle Viaduct / SR-99 Tunnel', type: 'road', status: 'damaged', location: 'Seattle, WA', lastInspected: new Date('2026-03-16'), damageLevel: 'severe', repairEstimate: 1200000000, priority: 'critical', notes: 'Tunnel alignment shifted 6 inches. Multiple wall panel failures. Closed indefinitely.', incidentId: incidents[4].id },
      { name: 'King County Cell Tower Network', type: 'communication_tower', status: 'offline', location: 'Seattle, WA', lastInspected: new Date('2026-03-16'), damageLevel: 'moderate', repairEstimate: 25000000, priority: 'critical', notes: '40% of cell towers offline due to power loss and structural damage. Temporary COWs (Cell on Wheels) being deployed.', incidentId: incidents[4].id },
      { name: 'Baton Rouge Water Treatment Plant', type: 'water_system', status: 'damaged', location: 'Baton Rouge, LA', lastInspected: new Date('2026-03-17'), damageLevel: 'moderate', repairEstimate: 12000000, priority: 'high', notes: 'Chemical contamination risk from industrial explosion. Water testing underway. Boil water advisory issued.', incidentId: incidents[5].id },
      { name: 'Joplin Unified School District Complex', type: 'school', status: 'destroyed', location: 'Joplin, MO', lastInspected: new Date('2026-03-15'), damageLevel: 'destroyed', repairEstimate: 120000000, priority: 'medium', notes: 'Three school buildings destroyed. Students relocated to temporary facilities in surrounding districts.', incidentId: incidents[2].id },
      { name: 'Anchorage Government Hill Road Network', type: 'road', status: 'damaged', location: 'Anchorage, AK', lastInspected: new Date('2026-03-13'), damageLevel: 'minor', repairEstimate: 8000000, priority: 'medium', notes: 'Road surface cracking and minor sinkholes. Temporary repairs in progress. Full resurfacing needed in spring.', incidentId: incidents[14].id },
      { name: 'Tacoma Narrows Power Substation', type: 'power_grid', status: 'under_repair', location: 'Tacoma, WA', lastInspected: new Date('2026-03-17'), damageLevel: 'moderate', repairEstimate: 35000000, priority: 'high', notes: 'Transformer damage from earthquake. Backup power routing established. Repair crews on site.', incidentId: incidents[4].id },
      { name: 'Fort Myers Beach Matanzas Pass Bridge', type: 'bridge', status: 'under_repair', location: 'Fort Myers, FL', lastInspected: new Date('2026-02-01'), damageLevel: 'moderate', repairEstimate: 65000000, priority: 'high', notes: 'Bridge reopened to emergency vehicles only. Full repair estimated 6 months.', incidentId: incidents[10].id },
      { name: 'Boulder Creek Trail Bridge System', type: 'bridge', status: 'destroyed', location: 'Boulder, CO', lastInspected: new Date('2026-02-25'), damageLevel: 'severe', repairEstimate: 4500000, priority: 'low', notes: 'Three pedestrian bridges washed away. Replacement planned for summer construction season.', incidentId: incidents[8].id },
      { name: 'Moore City Hall', type: 'government_building', status: 'operational', location: 'Moore, OK', lastInspected: new Date('2026-03-01'), damageLevel: 'minor', repairEstimate: 250000, priority: 'low', notes: 'Minor roof damage repaired. Building fully operational as emergency operations center.', incidentId: incidents[9].id },
      { name: 'Harborview Medical Center', type: 'hospital', status: 'damaged', location: 'Seattle, WA', lastInspected: new Date('2026-03-17'), damageLevel: 'moderate', repairEstimate: 150000000, priority: 'critical', notes: 'Structural cracks in east wing. Patient evacuation of 3rd and 4th floors completed. Operating at 60% capacity.', incidentId: incidents[4].id },
    ]);
    console.log('Infrastructure seeded.');

    // ===== THREAT ANALYSES =====
    await db.ThreatAnalysis.bulkCreate([
      { threatType: 'Hurricane - Category 5 Intensification', region: 'Gulf of Mexico', riskLevel: 'extreme', probability: 0.35, potentialImpact: 'If Hurricane Elena intensifies to Category 5 before landfall, storm surge could reach 25 feet. Catastrophic damage potential to petrochemical infrastructure.', affectedPopulation: 4500000, description: 'Warm Gulf waters and low wind shear creating conditions for rapid intensification. Sea surface temperatures 2 degrees above normal.', mitigationSteps: ['Expand evacuation zone', 'Pre-position additional rescue assets', 'Coordinate with petrochemical facilities for emergency shutdown', 'Activate mutual aid with neighboring states'], status: 'monitoring', analyzedBy: 'AI Threat Analysis System', analysisDate: new Date('2026-03-15'), aiConfidence: 0.78 },
      { threatType: 'Cascadia Subduction Zone Aftershock', region: 'Pacific Northwest', riskLevel: 'high', probability: 0.65, potentialImpact: 'Significant aftershock (M6.0+) could cause additional building collapses in weakened structures throughout Seattle metro area.', affectedPopulation: 3800000, description: 'Historical data shows 70% probability of M6.0+ aftershock within 7 days of mainshock. Multiple fault segments may be activated.', mitigationSteps: ['Evacuate all red-tagged buildings', 'Deploy additional structural engineers', 'Pre-position heavy rescue equipment', 'Establish temporary shelters away from damaged structures'], status: 'escalated', analyzedBy: 'USGS Seismology Team + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.85 },
      { threatType: 'Secondary Chemical Release', region: 'Baton Rouge, LA', riskLevel: 'high', probability: 0.45, potentialImpact: 'Adjacent chemical storage tanks weakened by blast. Secondary release could double the evacuation zone and expose 250,000 additional residents.', affectedPopulation: 250000, description: 'Structural integrity of 3 neighboring storage tanks compromised. Wind shift could direct any release toward populated residential areas.', mitigationSteps: ['Emergency tank inspection and pressure relief', 'Pre-position additional hazmat teams', 'Prepare expanded evacuation routes', 'Distribute potassium iodide to at-risk population'], status: 'monitoring', analyzedBy: 'EPA Hazmat Assessment + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.72 },
      { threatType: 'Dam Failure - Mississippi Tributary', region: 'Mississippi River Valley', riskLevel: 'moderate', probability: 0.2, potentialImpact: 'Wolf River dam showing stress under record water levels. Failure would cause catastrophic flooding in eastern Memphis suburbs.', affectedPopulation: 150000, description: 'Dam built in 1962, last major inspection 2019. Current water level exceeds design parameters by 15%.', mitigationSteps: ['Emergency dam inspection', 'Deploy monitoring sensors', 'Prepare downstream evacuation plans', 'Pre-position sandbags and pumps'], status: 'monitoring', analyzedBy: 'Army Corps of Engineers + AI', analysisDate: new Date('2026-03-14'), aiConfidence: 0.68 },
      { threatType: 'Wildfire Firestorm Development', region: 'Northern California', riskLevel: 'extreme', probability: 0.55, potentialImpact: 'Hot, dry, windy conditions could create a firestorm. Unprecedented fire behavior could overwhelm suppression efforts and threaten Chico.', affectedPopulation: 90000, description: 'Red flag warning conditions combined with 150,000-acre fire creating own weather patterns. Pyrocumulus clouds observed.', mitigationSteps: ['Pre-position evacuation resources for Chico', 'Request additional air tanker support', 'Establish firebreaks on south side of fire', 'Activate mutual aid with Oregon and Nevada'], status: 'escalated', analyzedBy: 'CAL FIRE Intelligence + AI', analysisDate: new Date('2026-03-13'), aiConfidence: 0.81 },
      { threatType: 'Tsunami Wave Impact', region: 'Hawaii', riskLevel: 'high', probability: 0.7, potentialImpact: 'First wave arrival may generate 6-10 foot tsunami. Subsequent waves could be larger. Significant coastal damage expected.', affectedPopulation: 980000, description: 'Seismic data from Aleutian Islands earthquake indicates strong tsunami generation. DART buoys confirming wave propagation.', mitigationSteps: ['Complete coastal evacuation', 'Move boats to deep water', 'Activate all warning sirens', 'Close all beaches and harbors', 'Position rescue teams at elevation'], status: 'escalated', analyzedBy: 'Pacific Tsunami Warning Center + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.88 },
      { threatType: 'H5N1 Human Transmission', region: 'Midwest United States', riskLevel: 'moderate', probability: 0.15, potentialImpact: 'If sustained human-to-human transmission occurs, could trigger pandemic response across agricultural heartland.', affectedPopulation: 500000, description: 'Current cases linked to direct poultry contact. No confirmed human-to-human transmission yet but genomic sequencing shows concerning mutations.', mitigationSteps: ['Enhanced surveillance at hospitals', 'Stockpile antivirals', 'Prepare vaccination campaign', 'Implement worker protection protocols'], status: 'monitoring', analyzedBy: 'CDC Epidemiology + AI', analysisDate: new Date('2026-03-05'), aiConfidence: 0.62 },
      { threatType: 'Infrastructure Cascade Failure', region: 'Seattle Metro', riskLevel: 'high', probability: 0.5, potentialImpact: 'Loss of multiple infrastructure systems simultaneously could create humanitarian crisis. Water, power, communications, and transportation all compromised.', affectedPopulation: 3800000, description: 'Earthquake damaged water mains, power grid, cell towers, and roads simultaneously. Cascading failures as backup systems overwhelmed.', mitigationSteps: ['Prioritize water system restoration', 'Deploy mobile cell towers', 'Establish emergency generator networks', 'Create alternative transportation corridors'], status: 'escalated', analyzedBy: 'FEMA Infrastructure Analysis + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.83 },
      { threatType: 'Storm Surge Inland Penetration', region: 'Houston Ship Channel', riskLevel: 'extreme', probability: 0.6, potentialImpact: 'Storm surge penetrating inland via Houston Ship Channel could flood petrochemical facilities storing billions of gallons of hazardous materials.', affectedPopulation: 2000000, description: 'Hurricane Elena storm surge models show 15-20 foot surge. Ship Channel acts as funnel, potentially amplifying surge height.', mitigationSteps: ['Emergency shutdown of Ship Channel facilities', 'Deploy surge barriers', 'Coordinate Coast Guard closure of channel', 'Activate environmental response teams'], status: 'escalated', analyzedBy: 'NOAA Storm Surge Unit + AI', analysisDate: new Date('2026-03-15'), aiConfidence: 0.79 },
      { threatType: 'Tornado Outbreak Continuation', region: 'Central United States', riskLevel: 'moderate', probability: 0.4, potentialImpact: 'Atmospheric conditions remain favorable for continued tornado production. Additional EF3+ tornadoes possible across Kansas and Oklahoma.', affectedPopulation: 2000000, description: 'Upper-level jet stream pattern persists over central plains. Moisture return from Gulf providing instability.', mitigationSteps: ['Maintain tornado watches', 'Keep USAR teams on standby', 'Ensure shelter availability in threatened areas', 'Pre-position additional ambulances'], status: 'monitoring', analyzedBy: 'NOAA SPC + AI', analysisDate: new Date('2026-03-16'), aiConfidence: 0.74 },
      { threatType: 'Levee System Failure', region: 'Lower Mississippi', riskLevel: 'moderate', probability: 0.25, potentialImpact: 'Prolonged high water may cause additional levee failures south of Memphis. Agricultural losses could exceed $5 billion.', affectedPopulation: 300000, description: 'Three levee breaches already occurred. Remaining levees under extreme pressure. Some levees not improved since 1960s.', mitigationSteps: ['24/7 levee monitoring patrols', 'Pre-position pumps and sandbags', 'Prepare agricultural evacuation plans', 'Request Army Corps emergency repair authorization'], status: 'monitoring', analyzedBy: 'Army Corps of Engineers + AI', analysisDate: new Date('2026-03-14'), aiConfidence: 0.71 },
      { threatType: 'Compound Disaster - Hurricane + Chemical', region: 'Louisiana Gulf Coast', riskLevel: 'extreme', probability: 0.15, potentialImpact: 'If developing tropical system impacts Baton Rouge while chemical incident unresolved, would create unprecedented compound disaster.', affectedPopulation: 500000, description: 'Tropical depression in Caribbean could reach Louisiana in 7 days. Chemical plume from industrial explosion still not fully contained.', mitigationSteps: ['Monitor tropical development closely', 'Accelerate chemical containment efforts', 'Prepare regional evacuation plans', 'Request federal disaster declaration expansion'], status: 'identified', analyzedBy: 'FEMA Risk Analysis + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.65 },
      { threatType: 'Liquefaction Risk - Tacoma Port', region: 'Tacoma, WA', riskLevel: 'high', probability: 0.55, potentialImpact: 'Soil liquefaction threatens port infrastructure. Loss of port operations would disrupt regional supply chain critical for disaster recovery.', affectedPopulation: 500000, description: 'Geotechnical surveys show extensive liquefaction in port fill areas. Additional seismic activity could cause catastrophic ground failure.', mitigationSteps: ['Close port to heavy equipment', 'Conduct emergency geotechnical survey', 'Identify alternative supply routes', 'Restrict access to vulnerable areas'], status: 'monitoring', analyzedBy: 'USGS Geotechnical + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.76 },
      { threatType: 'Public Health Crisis - Contaminated Floodwater', region: 'Houston Metro', riskLevel: 'high', probability: 0.7, potentialImpact: 'Floodwaters contaminated with sewage, chemicals, and debris creating disease outbreak risk. Waterborne illness could affect thousands.', affectedPopulation: 500000, description: 'Water sampling shows E. coli levels 200x safe limits. Chemical contaminants from industrial areas mixing with floodwater. Standing water breeding mosquitoes.', mitigationSteps: ['Distribute water purification supplies', 'Deploy mobile medical clinics', 'Begin mosquito spraying operations', 'Issue public health advisories', 'Pre-position antibiotics and antiviral medications'], status: 'escalated', analyzedBy: 'CDC Environmental Health + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.87 },
      { threatType: 'Secondary Earthquake - Seattle Fault', region: 'Seattle, WA', riskLevel: 'moderate', probability: 0.1, potentialImpact: 'The shallow Seattle Fault could be triggered by stress transfer from Cascadia event. A M6.5 on this fault would be directly under downtown.', affectedPopulation: 700000, description: 'Historical evidence shows Cascadia events can trigger crustal faults. The Seattle Fault last ruptured ~1100 years ago.', mitigationSteps: ['Enhanced seismic monitoring', 'Prepare for potential secondary event', 'Communicate risk to public without causing panic', 'Ensure emergency plans account for compound seismic scenario'], status: 'identified', analyzedBy: 'USGS Seismology + AI', analysisDate: new Date('2026-03-17'), aiConfidence: 0.58 },
    ]);
    console.log('Threat Analyses seeded.');

    console.log('\n=== Seeding Complete ===');
    console.log('Admin user: admin@disaster-response.gov / Admin123!');
    console.log('All models seeded with 15 records each.\n');

    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error);
    process.exit(1);
  }
};

seed();
